spring.application.name=backend

gemini.api.key=AQ.Ab8RN6I6P_ya5OaM7pbFOZVMSbo4hBIXkBej7ZThOERTK_abdg
tavily.api.key=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
jsearch.api.key=3792d30b1dmsh81f7778d02b75bdp1f5c05jsn82947e1d84cb